# Principal Component Analysis

In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

### Import Datas

In [2]:
datas = pd.read_csv('wine.csv')
X = datas.iloc[:, 0:13].values
y = datas.iloc[:, -1:].values

### Split Test and Train Sets

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 0)

### Import Libraries

### Feature Scaling

In [4]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

### PCA

In [8]:
from sklearn.decomposition import PCA

pca = PCA(n_components = 2) # n_components = how many dimension you want
X_train2 = pca.fit_transform(X_train)
X_test2 = pca.transform(X_test)

### Logistic Regression

In [10]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)
y_predict = classifier.predict(X_test)

classifier2 = LogisticRegression(random_state = 0)
classifier2.fit(X_train2, y_train)
y_predict2 = classifier2.predict(X_test2)

c:\Users\AMD\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\AMD\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### Confusion Matrix

In [14]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_predict) #without PCA
print(cm)

cm2 = confusion_matrix(y_test, y_predict2) #with PCA
print(cm2)

[[20  0  0]
 [ 0 24  0]
 [ 0  0 15]]
[[20  0  0]
 [ 1 23  0]
 [ 0  0 15]]
